name: "Install dependencies"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          echo "Starting dependency installation..."
          /bin/bash "${GITHUB_WORKSPACE}/automation_tools/install_dependencies.sh"