name: "Install dependencies"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: "Install dependencies"
        run: ./automation_tools/install_dependencies.sh